language: java
sudo: false

jdk:
- openjdk8

install:

- mvn clean install -B -V

script:
- sh ./check_format.sh

after_success:
  - bash <(curl -s https://codecov.io/bash) -t f47e7712-7c14-4489-9b1f-e9586f5248c7
